name: Build all samples
on: [push, pull_request]
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: 'Build all samples using JShell'
        run: java src/Builder.java
      - name: 'Check automation for updating versions'
        run: java src/Updater.java 42
        if: github.repository == 'junit-team/junit5-samples' && github.ref == 'refs/heads/main'
