name: Build all samples
on:
  push:
    branches:
      - main
      - 'r5.*'
  pull_request:
    branches:
      - '*'
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: 'Set up JDK 21'
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          java-version: 21
          distribution: temurin
      - name: 'Build all samples using JShell'
        run: java src/Builder.java
      - name: 'Check automation for updating versions'
        run: java src/Updater.java 42
        if: github.repository == 'junit-team/junit5-samples' && github.ref == 'refs/heads/main'
