name: Build all samples
on:
  push:
    branches:
      - main
      - 'r5.*'
  pull_request:
    branches:
      - '*'
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: 'Set up JDK 21'
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: 21
          distribution: temurin
      - uses: sbt/setup-sbt@8ee7ec888f2a1af33ba66f994c4fb05aaf23e7d0 # v1.1.6
      - name: 'Build all samples using JShell'
        run: java src/Builder.java
      - name: 'Check automation for updating versions'
        run: java src/Updater.java 42
        if: github.repository == 'junit-team/junit5-samples' && github.ref == 'refs/heads/main'
      - name: 'Check automation for injecting a staging repository'
        run: java src/StagingRepoInjector.java https://example.org/service/local/repositories/orgjunit-1234/content
        if: github.repository == 'junit-team/junit5-samples' && github.ref == 'refs/heads/main'
