name: Build starters using JUnit SNAPSHOT
on:
  push:
    branches:
      - main
      - 'r5.*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 6 * * *'
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: 'Set up JDK 21'
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
        with:
          java-version: 21
          distribution: temurin
      - name: 'JUnit 5 SNAPSHOT build: Gradle'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-gradle && ./gradlew test --console plain --build-file build-SNAPSHOT.gradle
      - name: 'JUnit 5 SNAPSHOT build: Maven'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-maven && ./mvnw test --batch-mode --file pom-SNAPSHOT.xml
