name: Build starters using JUnit SNAPSHOT
on:
  push:
  pull_request:
  schedule:
  - cron: '0 6 * * *'
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: 'Set up JDK 21'
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4
        with:
          java-version: 21
          distribution: temurin
      - name: 'JUnit 5 SNAPSHOT build: Gradle'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-gradle && ./gradlew test --console plain --build-file build-SNAPSHOT.gradle
      - name: 'JUnit 5 SNAPSHOT build: Maven'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-maven && ./mvnw test --batch-mode --file pom-SNAPSHOT.xml
