name: Build starters using JUnit SNAPSHOT
on:
  push:
    branches:
      - main
      - 'r5.*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 6 * * *'
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: 'Set up JDK 21'
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          java-version: 21
          distribution: temurin
      - name: 'JUnit 5 SNAPSHOT build: Gradle'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-gradle && ./gradlew test --console plain --build-file build-SNAPSHOT.gradle
      - name: 'JUnit 5 SNAPSHOT build: Maven'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-maven && ./mvnw test --batch-mode --file pom-SNAPSHOT.xml
