name: Verify HTTPS URLs are used

on:
  push:
    branches:
      - main
      - 'r5.*'
      - 'r6.*'
      - 'releases/**'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  nohttp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 'Run nohttp'
        uses: jbangdev/jbang-action@67bedb972cb646703ddaf6c94d124b9ff873c1a6 # v0.139.3
        with:
          script: io.spring.nohttp:nohttp-cli:0.0.9
          scriptargs: "-D=\\.git -D=build -D=target -D=apache-ant-.+ -F=maven-wrapper\\.properties -F=mvnw\\.cmd -Fmvnw -FMODULE.bazel.lock"
